name: Learncourse
description: Приложение для онлайн-курсов
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  web: ^1.1.1
  supabase_flutter: ^2.3.0
  go_router: ^13.0.0
  provider: ^6.1.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  html_editor_enhanced: ^2.6.0
  flutter_inappwebview: ^6.0.0
  flutter_widget_from_html_core: ^0.15.0
  html: ^0.15.4
  universal_html: ^2.2.4
  flutter_cache_manager: ^3.3.1
  video_player: ^2.8.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.0

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon/logo.png
    - assets/icon/logo_light.png

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  image_path: "assets/icon/app_icon.png"